import streamlit as st

st.set_page_config(page_title="PHL 201 Exam Quiz", page_icon="🧠", layout="wide")

if 'answers' not in st.session_state:
    st.session_state.answers = {}

# All 120 questions - compact format
questions = [
    {"id": 1, "q": "What is epistemology?", "opts": ["The study of being and existence", "The study of knowledge and truth", "The study of ethics and morality", "The study of logic and argumentation"], "ans": 1, "sec": "Epistemology", "exp": "Epistemology is the branch of philosophy concerned with the theory of knowledge."},
    {"id": 2, "q": "The classical definition of knowledge is:", "opts": ["True belief", "Justified true belief", "Certain belief", "Popular belief"], "ans": 1, "sec": "Epistemology", "exp": "The classical definition requires: belief, truth, and justification."},
    {"id": 3, "q": "The Gettier problem challenges:", "opts": ["The existence of truth", "The classical definition of knowledge as justified true belief", "The possibility of belief", "The need for justification"], "ans": 1, "sec": "Epistemology", "exp": "Gettier showed cases where justified true belief still doesn't seem to be knowledge."},
    {"id": 4, "q": "Rationalism emphasizes:", "opts": ["Experience only", "Reason and logic", "Authority", "Intuition only"], "ans": 1, "sec": "Epistemology", "exp": "Rationalism holds that reason is the primary source of knowledge."},
    {"id": 5, "q": "Empiricism emphasizes:", "opts": ["Reason only", "Sensory experience and observation", "Revelation", "Mathematical proof"], "ans": 1, "sec": "Epistemology", "exp": "Empiricism holds that knowledge comes from sensory experience."},
    {"id": 6, "q": "A priori knowledge:", "opts": ["Requires experience", "Can be known independently of experience", "Comes from authorities", "Changes over time"], "ans": 1, "sec": "Epistemology", "exp": "A priori knowledge can be known through reason alone."},
    {"id": 7, "q": "A posteriori knowledge requires:", "opts": ["Pure reasoning only", "Experience and observation", "Mathematical proof", "Authority confirmation"], "ans": 1, "sec": "Epistemology", "exp": "A posteriori knowledge depends on empirical evidence."},
    {"id": 8, "q": "Skepticism questions:", "opts": ["Religious beliefs only", "Whether knowledge is possible", "Scientific claims only", "Arguments only"], "ans": 1, "sec": "Epistemology", "exp": "Skepticism questions whether we can truly know anything."},
    {"id": 9, "q": "Foundationalism claims:", "opts": ["All beliefs are equal", "Some beliefs are basic and need no justification from others", "No beliefs can be justified", "Only empirical beliefs count"], "ans": 1, "sec": "Epistemology", "exp": "Foundationalism argues some beliefs are self-evident foundations."},
    {"id": 10, "q": "Coherentism argues:", "opts": ["Only foundations matter", "Beliefs are justified by fitting coherently together", "No justification is possible", "Only experience matters"], "ans": 1, "sec": "Epistemology", "exp": "Coherentism holds beliefs are justified by mutual support."},
    {"id": 11, "q": "Reliabilism judges knowledge based on:", "opts": ["Popular consensus", "Whether the belief-forming process is reliable", "Authority endorsement", "Emotional certainty"], "ans": 1, "sec": "Epistemology", "exp": "Reliabilism focuses on the reliability of belief-forming processes."},
    {"id": 12, "q": "Knowledge differs from opinion because:", "opts": ["Knowledge is popular", "Knowledge has rational justification and corresponds to reality", "Knowledge is easier", "Knowledge never changes"], "ans": 1, "sec": "Epistemology", "exp": "Knowledge requires both truth and justification."},
    {"id": 13, "q": "Internalism in epistemology holds that:", "opts": ["Knowledge comes from within", "The factors that justify belief must be accessible to the believer", "Only internal states exist", "The external world is irrelevant"], "ans": 1, "sec": "Epistemology", "exp": "Internalism requires justification to be internally accessible."},
    {"id": 14, "q": "Externalism in epistemology argues:", "opts": ["Only external things exist", "Justification can depend on factors outside the believer's awareness", "Knowledge is impossible", "Only empirical knowledge counts"], "ans": 1, "sec": "Epistemology", "exp": "Externalism allows external factors to justify beliefs."},
    {"id": 15, "q": "The correspondence theory of truth states:", "opts": ["Truth is what most believe", "Truth consists in agreement of thoughts with reality", "Truth is whatever works", "Truth doesn't exist"], "ans": 1, "sec": "Epistemology", "exp": "Correspondence theory says truth matches reality."},
    {"id": 16, "q": "The tripartite definition of knowledge requires:", "opts": ["Only truth", "Belief, truth, and justification", "Only justification", "Only belief"], "ans": 1, "sec": "Epistemology", "exp": "Tripartite means three parts: belief, truth, justification."},
    {"id": 17, "q": "Fallibilism holds that:", "opts": ["We can never be wrong", "Knowledge doesn't require absolute certainty", "All beliefs are false", "Only certain beliefs count as knowledge"], "ans": 1, "sec": "Epistemology", "exp": "Fallibilism accepts knowledge without certainty."},
    {"id": 18, "q": "The regress problem in epistemology concerns:", "opts": ["Going backwards in time", "The infinite chain of justification for beliefs", "Forgetting information", "Repeating mistakes"], "ans": 1, "sec": "Epistemology", "exp": "The regress problem asks what stops the infinite chain of justification."},
    {"id": 19, "q": "Virtue epistemology focuses on:", "opts": ["Moral virtues only", "Intellectual virtues and excellences in knowing", "Social virtues", "Physical abilities"], "ans": 1, "sec": "Epistemology", "exp": "Virtue epistemology emphasizes intellectual character traits."},
    {"id": 20, "q": "Contextualism in epistemology claims:", "opts": ["Context never matters", "Knowledge attributions are context-sensitive", "Only context matters", "Context is irrelevant to truth"], "ans": 1, "sec": "Epistemology", "exp": "Contextualism says knowledge standards vary by context."},
    {"id": 21, "q": "The value problem asks:", "opts": ["How much knowledge costs", "Why knowledge is more valuable than mere true belief", "Which knowledge is most important", "How to measure knowledge"], "ans": 1, "sec": "Epistemology", "exp": "The value problem asks why knowledge beats lucky true belief."},
    {"id": 22, "q": "What distinguishes knowledge from lucky guesses?", "opts": ["Knowledge is always certain", "Knowledge has proper justification and isn't accidental", "Knowledge is more popular", "Knowledge is simpler"], "ans": 1, "sec": "Epistemology", "exp": "Knowledge requires non-accidental justification."},
    {"id": 23, "q": "According to course readings, precise definition matters because:", "opts": ["It sounds academic", "Imprecise claims cannot be properly evaluated", "It makes arguments longer", "It confuses opponents"], "ans": 1, "sec": "Epistemology", "exp": "Precision enables proper evaluation of claims."},
    {"id": 24, "q": "Epistemic circularity occurs when:", "opts": ["Using circular reasoning", "Using a source of knowledge to validate itself", "Avoiding all reasoning", "Only trusting authorities"], "ans": 1, "sec": "Epistemology", "exp": "Epistemic circularity uses a source to justify itself."},
    {"id": 25, "q": "The problem of the criterion refers to:", "opts": ["Measuring difficulty", "The circular challenge of needing criteria for truth to establish criteria", "Education cost", "Learning time"], "ans": 1, "sec": "Epistemology", "exp": "We need criteria to know truth but need truth to establish criteria."},
    {"id": 26, "q": "Modal epistemology deals with:", "opts": ["Only necessary truths", "Knowledge of possibility and necessity", "Only empirical facts", "Only logical truths"], "ans": 1, "sec": "Epistemology", "exp": "Modal epistemology studies knowledge of possibility and necessity."},
    {"id": 27, "q": "What is a philosophical claim?", "opts": ["An emotion", "A declarative sentence that can be true or false", "A question", "A belief without justification"], "ans": 1, "sec": "Epistemology", "exp": "A claim is a statement with a truth value."},
    {"id": 28, "q": "A vague claim:", "opts": ["Is about abstracts", "Uses imprecise words with unclear boundaries", "Is controversial", "Is complex"], "ans": 1, "sec": "Epistemology", "exp": "Vague claims lack clear boundaries."},
    {"id": 29, "q": "An ambiguous claim:", "opts": ["Is false", "Can have several possible meanings", "Is simple", "Needs expertise"], "ans": 1, "sec": "Epistemology", "exp": "Ambiguous claims have multiple interpretations."},
    {"id": 30, "q": "To avoid vagueness:", "opts": ["Use technical terms", "Define terms through examples, synonyms, or explanations", "Avoid topics", "Discuss facts only"], "ans": 1, "sec": "Epistemology", "exp": "Clear definitions reduce vagueness."},
    {"id": 31, "q": "According to Plato, the world we perceive through our senses is:", "opts": ["The most real and reliable source of knowledge", "An imperfect copy of a more perfect reality", "An illusion that doesn't exist at all", "The only world that exists"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Plato believed the physical world is an imperfect copy of the Forms."},
    {"id": 32, "q": "In Plato's Theory of Forms, what makes the Forms 'more real' than material objects?", "opts": ["Forms are bigger and more powerful", "Forms are eternal, unchanging, and perfect while material things are temporary and flawed", "Forms can be seen with our eyes", "Forms are located in a specific place"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Forms are eternal, unchanging, and perfect."},
    {"id": 33, "q": "What does the 'participation' relationship mean in Plato's theory?", "opts": ["Forms actively participate in creating the world", "Material objects are imperfect copies that 'participate in' perfect Forms", "Humans participate in Forms through ceremonies", "Forms and objects are equal participants"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Physical objects participate in Forms by resembling them."},
    {"id": 34, "q": "According to Plato, why can we recognize an imperfect drawn triangle?", "opts": ["Because we learned geometry", "Because our soul has knowledge of the perfect Form of Triangle from before birth", "Because all triangles are actually perfect", "Because recognition is learned behavior"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Our souls remember the Forms from before birth (recollection)."},
    {"id": 35, "q": "What is the Form of the Good in Plato's theory?", "opts": ["Just another Form", "The highest Form that makes all other Forms knowable", "A form in human minds only", "The least important Form"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "The Form of the Good is the highest Form, source of all reality."},
    {"id": 36, "q": "In Plato's Divided Line, which represents the highest knowledge?", "opts": ["Images and shadows (eikasia)", "Physical objects (pistis)", "Mathematical reasoning (dianoia)", "Knowledge of Forms through dialectic (noesis)"], "ans": 3, "sec": "Plato's Theory of Forms", "exp": "Noesis (knowledge of Forms) is the highest level."},
    {"id": 37, "q": "Which would Plato consider closest to true reality?", "opts": ["A photograph of a sunset", "The actual sunset", "Mathematical equations of light", "The Form of Beauty itself"], "ans": 3, "sec": "Plato's Theory of Forms", "exp": "The Form of Beauty is truest reality."},
    {"id": 38, "q": "What does Plato mean when he says philosophers should rule?", "opts": ["Philosophers are more ambitious", "Only philosophers have seen true reality and can guide others", "Philosophers are better at making money", "Philosophy is easiest to master"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Philosopher-kings understand true reality and the Good."},
    {"id": 39, "q": "How does Plato explain understanding abstract mathematical concepts?", "opts": ["Mathematics is learned through experience", "The soul has prior knowledge of mathematical Forms", "Mathematical concepts are conventions", "Mathematics doesn't really exist"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "The soul remembers mathematical Forms from before birth."},
    {"id": 40, "q": "According to Plato, justice in the soul and justice in the state:", "opts": ["Have no relationship", "Both involve the same structure: reason ruling spirit and appetite", "Political justice is more important", "Individual justice is impossible without political"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Same Form manifests in both soul and state."},
    {"id": 41, "q": "In the Cave Allegory, shadows represent:", "opts": ["Evil or false ideas", "Sensory experiences we mistake for ultimate reality", "Mathematical concepts", "Political propaganda"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Shadows represent the physical world we perceive."},
    {"id": 42, "q": "The journey from cave to sunlight represents:", "opts": ["Growing up", "The process of philosophical education and enlightenment", "Escaping political oppression", "Learning to use senses better"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "The journey represents philosophical education from ignorance to knowledge."},
    {"id": 43, "q": "Why does the escaped prisoner return to the cave?", "opts": ["The outside was an illusion", "He wants to rule the prisoners", "He feels a duty to help others reach enlightenment", "He is forced to return"], "ans": 2, "sec": "Plato's Theory of Forms", "exp": "He returns out of moral duty to help free others."},
    {"id": 44, "q": "According to Plato, why do people resist philosophical truth?", "opts": ["They are evil or stupid", "Truth is painful and they prefer comfortable illusions", "Philosophers explain poorly", "There is no real truth"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Truth is difficult and challenges comfortable illusions."},
    {"id": 45, "q": "The sun in the Cave Allegory represents:", "opts": ["Physical warmth", "The Form of the Good", "Human emotions", "Political power"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "The sun represents the Form of the Good."},
    {"id": 46, "q": "Plato's view on knowledge and moral responsibility:", "opts": ["Knowledge has nothing to do with morality", "Those with knowledge have a duty to help others", "Knowledge makes people selfish", "Only some deserve knowledge"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Knowledge brings moral responsibility to help others."},
    {"id": 47, "q": "How does Plato explain moral knowledge?", "opts": ["From cultural conditioning", "From recognizing eternal moral Forms like Justice and Good", "There is no moral knowledge", "Moral knowledge is emotional"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Moral knowledge means grasping eternal moral Forms."},
    {"id": 48, "q": "Why is the physical world less real than the Forms?", "opts": ["It doesn't exist at all", "It's constantly changing and imperfect, while Forms are eternal and perfect", "It's too small", "It's evil while Forms are good"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Physical things are temporary, changing, and imperfect."},
    {"id": 49, "q": "How does Plato explain why mathematical truths are universal?", "opts": ["Different cultures create different mathematics", "Mathematical Forms exist eternally and can be discovered", "Mathematics is just convention", "Mathematical truths aren't universal"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "Mathematical Forms exist independently and eternally."},
    {"id": 50, "q": "What is Aristotle's 'Third Man' argument?", "opts": ["There must be three versions of every Form", "If humans resemble the Form of Human, we need another Form to explain that, leading to infinite regress", "Only three people can understand each Form", "Forms exist in groups of three"], "ans": 1, "sec": "Plato's Theory of Forms", "exp": "The Third Man argument shows an infinite regress problem."},
    {"id": 51, "q": "Why was Socrates put on trial?", "opts": ["For stealing money", "For corrupting the youth and not believing in the gods of the state", "For supporting Athens' enemies", "For teaching without a license"], "ans": 1, "sec": "Socrates", "exp": "Socrates was charged with corrupting youth and impiety."},
    {"id": 52, "q": "Socrates' response to the Oracle saying he was wisest?", "opts": ["He accepted it as proof of superiority", "He tested this by questioning people who claimed knowledge", "He rejected the Oracle", "He stopped doing philosophy"], "ans": 1, "sec": "Socrates", "exp": "Socrates tested the claim by questioning supposedly wise people."},
    {"id": 53, "q": "Socrates' method of questioning is designed to:", "opts": ["Prove he is smarter", "Show people they don't really know what they think they know", "Teach specific facts", "Win debates"], "ans": 1, "sec": "Socrates", "exp": "The Socratic method exposes ignorance and contradictions."},
    {"id": 54, "q": "In the Crito, why shouldn't Socrates escape?", "opts": ["Escape is impossible", "He has an obligation to obey the laws that gave him life", "He wants to be a martyr", "His friends refuse to help"], "ans": 1, "sec": "Socrates", "exp": "Socrates had an implicit agreement with Athens' laws."},
    {"id": 55, "q": "In his trial defense, Socrates compares himself to:", "opts": ["A wise teacher", "A gadfly that stings the state into action", "A military general", "A religious prophet"], "ans": 1, "sec": "Socrates", "exp": "Socrates called himself a gadfly to awaken Athens."},
    {"id": 56, "q": "'The unexamined life is not worth living' means:", "opts": ["Life without science is meaningless", "Life without philosophical self-reflection lacks value", "Only philosophers should live", "People should constantly worry"], "ans": 1, "sec": "Socrates", "exp": "We must examine our beliefs and values to live well."},
    {"id": 57, "q": "Socrates' claim that he knows nothing shows:", "opts": ["False modesty", "Intellectual humility and the beginning of true wisdom", "Knowledge is impossible", "He never studied"], "ans": 1, "sec": "Socrates", "exp": "Recognizing ignorance is the start of wisdom."},
    {"id": 58, "q": "Socrates' view on knowledge and virtue:", "opts": ["They are unrelated", "True knowledge leads to virtuous action - no one does wrong willingly", "Virtue is more important", "Knowledge corrupts virtue"], "ans": 1, "sec": "Socrates", "exp": "Virtue is knowledge - if you know good, you'll do it."},
    {"id": 59, "q": "What does philosophy literally mean?", "opts": ["The study of wisdom", "The love of wisdom", "The pursuit of truth", "The analysis of reality"], "ans": 1, "sec": "Socrates", "exp": "Philosophy means love of wisdom (philos + sophia)."},
    {"id": 60, "q": "The primary goal of philosophy:", "opts": ["To win arguments", "To achieve autonomy by examining beliefs and encouraging rational thinking", "To memorize ancient thinkers", "To prove knowledge is relative"], "ans": 1, "sec": "Socrates", "exp": "Philosophy develops autonomy through rational reflection."},
    {"id": 61, "q": "The three main traditional fields of philosophy:", "opts": ["Logic, ethics, and politics", "Epistemology, metaphysics, and ethics", "Theology, science, and morality", "Ancient, medieval, and modern"], "ans": 1, "sec": "Socrates", "exp": "Epistemology (knowledge), metaphysics (reality), ethics (morality)."},
    {"id": 62, "q": "Critical thinking involves:", "opts": ["Always disagreeing", "Disciplined thinking based on evidence and logic", "Criticizing without alternatives", "Following authority"], "ans": 1, "sec": "Socrates", "exp": "Critical thinking evaluates claims based on evidence and logic."},
    {"id": 63, "q": "Metaphysics addresses:", "opts": ["How we should treat people", "What we can know", "The most general characteristics of existence and reality", "How to construct arguments"], "ans": 2, "sec": "Socrates", "exp": "Metaphysics studies the fundamental nature of reality."},
    {"id": 64, "q": "Reasoning is:", "opts": ["Based on emotions", "The process of thinking by which we draw conclusions from evidence", "Only useful in math and science", "Should be avoided in philosophy"], "ans": 1, "sec": "Socrates", "exp": "Reasoning moves from evidence to conclusions logically."},
    {"id": 65, "q": "Philosophy is valuable because:", "opts": ["It guarantees wealth", "It helps achieve freedom, builds critical thinking, and cultivates awareness", "It provides easy answers", "It avoids difficult decisions"], "ans": 1, "sec": "Socrates", "exp": "Philosophy develops critical thinking and self-awareness."},
    {"id": 66, "q": "Pre-Socratic philosophers were significant because:", "opts": ["They relied on religious authority", "They moved from mythological to rational explanations", "They rejected reasoning", "They focused only on politics"], "ans": 1, "sec": "Socrates", "exp": "Pre-Socratics pioneered rational explanations over myths."},
    {"id": 67, "q": "In Phaedo, Socrates says the soul resembles:", "opts": ["The body", "Water", "Something divine, immortal, and intelligible", "A material object"], "ans": 2, "sec": "Socrates", "exp": "The soul is divine, immortal, and intelligible like Forms."},
    {"id": 68, "q": "A 'polluted' soul:", "opts": ["Becomes stronger", "Is dragged down to the visible world after death", "Immediately dies", "Gains wisdom"], "ans": 1, "sec": "Socrates", "exp": "Polluted souls are dragged back to the physical world."},
    {"id": 69, "q": "Plato's view on soul and body:", "opts": ["They are equal partners", "The soul should rule over the body", "The body should control the soul", "They are identical"], "ans": 1, "sec": "Socrates", "exp": "The rational soul should rule the body."},
    {"id": 70, "q": "Aristotle's 'highest end' for humans:", "opts": ["Pleasure and wealth", "Fame and recognition", "Happiness achieved through virtue and reason", "Knowledge of Forms in another world"], "ans": 2, "sec": "Socrates", "exp": "Eudaimonia (happiness) through virtue and reason."},
    {"id": 71, "q": "The 'Traditional Western View' of human nature:", "opts": ["Humans are essentially animals", "Humans are rational beings with immaterial souls designed for a purpose", "Humans are purely physical machines", "Humans are naturally evil"], "ans": 1, "sec": "Human Nature", "exp": "Traditional view: humans are rational with immortal souls."},
    {"id": 72, "q": "Darwin's three key ideas:", "opts": ["Evolution, creation, intelligent design", "Variation, struggle for existence, and natural selection", "Adaptation, mutation, survival", "Competition, cooperation, extinction"], "ans": 1, "sec": "Human Nature", "exp": "Variation, struggle, and natural selection."},
    {"id": 73, "q": "How Darwin challenges the Traditional Western view:", "opts": ["It proves souls don't exist", "It suggests humans evolved from animals, not specially designed", "It shows reason is useless", "It demonstrates purpose doesn't exist"], "ans": 1, "sec": "Human Nature", "exp": "Evolution suggests natural descent, not divine creation."},
    {"id": 74, "q": "Darwin on human mental faculties:", "opts": ["Completely different from animals", "No fundamental difference between human and higher mammal faculties", "Only humans have mental faculties", "Mental faculties don't exist"], "ans": 1, "sec": "Human Nature", "exp": "Humans differ from animals in degree, not kind."},
    {"id": 75, "q": "'Natural selection' means:", "opts": ["Humans choose traits to develop", "Nature decides who survives", "Favorable variations preserved, unfavorable destroyed through survival pressures", "All variations equally likely to survive"], "ans": 2, "sec": "Human Nature", "exp": "Advantageous traits are more likely to be passed on."},
    {"id": 76, "q": "Hobbes' materialist view:", "opts": ["Rational souls in physical bodies", "Complex physical machines driven by self-interest", "Divine beings in God's image", "Naturally good creatures corrupted by society"], "ans": 1, "sec": "Human Nature", "exp": "Hobbes saw humans as physical machines."},
    {"id": 77, "q": "'Psychological egoism' as defended by Hobbes:", "opts": ["People should be selfish", "All human actions are ultimately motivated by self-interest", "Psychology is the most important science", "Egos are psychological constructs"], "ans": 1, "sec": "Human Nature", "exp": "Psychological egoism: all actions stem from self-interest."},
    {"id": 78, "q": "Judeo-Christian view differs from Greek rationalism:", "opts": ["Denies rational capacities", "Adds humans made in God's image with moral will", "Rejects souls", "Claims humans are naturally perfect"], "ans": 1, "sec": "Human Nature", "exp": "Adds imago Dei and free moral will."},
    {"id": 79, "q": "Augustine's three disordered desires:", "opts": ["Reason, spirit, appetite", "Lust, curiosity, and pride", "Faith, hope, charity", "Mind, body, soul"], "ans": 1, "sec": "Human Nature", "exp": "Lust, curiosity, and pride corrupt the will."},
    {"id": 80, "q": "The mind-body problem:", "opts": ["How to keep both healthy", "How mind and body can be so different yet interact", "Whether brain is part of body", "Why we have thoughts and feelings"], "ans": 1, "sec": "Human Nature", "exp": "How can different substances (mental/physical) interact?"},
    {"id": 81, "q": "Consciousness is:", "opts": ["The ability to move", "Awareness of sensing, feeling, and thinking when awake", "Having a brain", "The ability to speak"], "ans": 1, "sec": "Human Nature", "exp": "Consciousness is subjective awareness of experiences."},
    {"id": 82, "q": "Dualism in philosophy of mind:", "opts": ["Two gods", "Humans consist of two kinds of things: mind and body", "Two types of bodies", "Consciousness has two parts"], "ans": 1, "sec": "Human Nature", "exp": "Dualism: mind (mental) and body (physical) are different."},
    {"id": 83, "q": "First great modern philosopher proposing clear dualism:", "opts": ["Plato", "Aristotle", "René Descartes", "David Hume"], "ans": 2, "sec": "Human Nature", "exp": "Descartes developed modern mind-body dualism."},
    {"id": 84, "q": "Descartes' famous conclusion on November 10, 1619:", "opts": ["God exists", "Body and mind are separate", "I think, therefore I am", "Everything is an illusion"], "ans": 2, "sec": "Human Nature", "exp": "Cogito, ergo sum - I think, therefore I am."},
    {"id": 85, "q": "According to Descartes, can you conceive yourself without a body?", "opts": ["No, impossible", "Yes, but not without a thinking mind", "Only in dreams", "Only after death"], "ans": 1, "sec": "Human Nature", "exp": "You can conceive of yourself without body, not without mind."},
    {"id": 86, "q": "Descartes' assumption about conceivability:", "opts": ["If you can conceive one thing without another, they must be different", "Conceiving something makes it real", "What you can't conceive doesn't exist", "Conceivability proves immortality"], "ans": 0, "sec": "Human Nature", "exp": "Conceivability implies real distinctness."},
    {"id": 87, "q": "Behaviorism's main claim:", "opts": ["Mind is a separate substance", "Mind is how you behave", "Mind doesn't exist", "Mind is the soul"], "ans": 1, "sec": "Human Nature", "exp": "Behaviorism: mental states are behavioral dispositions."},
    {"id": 88, "q": "Functionalism's main claim:", "opts": ["Mind is separate", "Mental activities are connections between inputs and outputs", "Only behavior matters", "Mind is identical to brain"], "ans": 1, "sec": "Human Nature", "exp": "Functionalism defines mind by functional role."},
    {"id": 89, "q": "Identity theory of mind:", "opts": ["Mind and body identical", "Mental states are identical with brain states", "All minds identical", "Identity is mental construct"], "ans": 1, "sec": "Human Nature", "exp": "Mental states are literally identical to brain states."},
    {"id": 90, "q": "Hume on the self:", "opts": ["An immortal soul", "Identical to physical body", "A bundle of constantly changing perceptions with no enduring self", "Created by God"], "ans": 2, "sec": "Human Nature", "exp": "Hume: no permanent self, just a bundle of perceptions."},
    {"id": 91, "q": "Two main components of an argument:", "opts": ["Facts and opinions", "Premises and conclusion", "Questions and answers", "Problems and solutions"], "ans": 1, "sec": "Logic", "exp": "Arguments have premises (reasons) and conclusion (claim)."},
    {"id": 92, "q": "A valid argument:", "opts": ["Premises are true", "Conclusion is true", "If premises true, conclusion must be true", "Everyone agrees"], "ans": 2, "sec": "Logic", "exp": "Validity: if premises were true, conclusion must follow."},
    {"id": 93, "q": "A sound argument is:", "opts": ["Sounds convincing", "A valid argument with true premises", "Everyone accepts it", "Made by authority"], "ans": 1, "sec": "Logic", "exp": "Sound = valid + actually true premises."},
    {"id": 94, "q": "What makes an argument invalid?", "opts": ["False premises", "Conclusion could be false even if premises true", "Unpopular conclusion", "Too many premises"], "ans": 1, "sec": "Logic", "exp": "Invalid: conclusion doesn't follow from premises."},
    {"id": 95, "q": "Deductive vs inductive arguments:", "opts": ["Deductive is longer", "Deductive aims for certainty, inductive for probability", "Deductive always true, inductive false", "No difference"], "ans": 1, "sec": "Logic", "exp": "Deductive: necessary conclusions; Inductive: probable conclusions."},
    {"id": 96, "q": "'Beg the question' means:", "opts": ["Ask many questions", "Assume what you're trying to prove (circular reasoning)", "Ask politely", "Raise an important issue"], "ans": 1, "sec": "Logic", "exp": "Begging the question is circular reasoning."},
    {"id": 97, "q": "Philosophical arguments differ from opinions because:", "opts": ["Always true", "Provide premises to support conclusions", "Are popular", "Are easy"], "ans": 1, "sec": "Logic", "exp": "Arguments provide reasoned support, opinions don't."},
    {"id": 98, "q": "Theoretical thinking holds:", "opts": ["Multiple views can be true", "If one view correct, different views must be incorrect", "All opinions equal", "Truth is relative"], "ans": 1, "sec": "Logic", "exp": "Contradictory views can't both be true."},
    {"id": 99, "q": "Anarchic thinking:", "opts": ["Studies different subjects", "Accepts multiple valid perspectives while theoretical seeks one", "Uses different methods", "Is ancient"], "ans": 1, "sec": "Logic", "exp": "Anarchic thinking allows multiple valid perspectives."},
    {"id": 100, "q": "Law of non-contradiction:", "opts": ["Everything contradicts", "Something cannot both be and not be in same respect at same time", "All contradictions true", "Logic impossible"], "ans": 1, "sec": "Logic", "exp": "X can't be both true and false simultaneously."},
    {"id": 101, "q": "Sartre on human freedom and choices:", "opts": ["Free but not responsible", "When we choose, we imply everyone should choose the same", "Freedom means avoiding choices", "Choices determined by God"], "ans": 1, "sec": "Logic", "exp": "Our choices reflect what we think humans should be."},
    {"id": 102, "q": "Sartre's 'anguish' means:", "opts": ["Physical pain", "Fear of death", "Recognition of our total responsibility when choosing", "Uncertainty about future"], "ans": 2, "sec": "Logic", "exp": "Anguish: recognizing our radical freedom and responsibility."},
    {"id": 103, "q": "Locke: what makes a person the same over time?", "opts": ["Immaterial soul", "Physical body", "Memory or consciousness of being that earlier person", "Social relationships"], "ans": 2, "sec": "Logic", "exp": "Personal identity consists in continuity of memory."},
    {"id": 104, "q": "Buddhist philosophy on the self:", "opts": ["An eternal soul", "A fleeting composite that dissolves and changes constantly", "Identical to physical body", "A creation of society"], "ans": 1, "sec": "Logic", "exp": "No-self (anatta): no permanent self exists."},
    {"id": 105, "q": "Hegel: how we become free and independent:", "opts": ["By isolating ourselves", "Through recognition from others who see us as free", "By accumulating wealth", "Through meditation alone"], "ans": 1, "sec": "Logic", "exp": "We become free through mutual recognition from others."},
    {"id": 106, "q": "Taylor: how identity is formed:", "opts": ["Through genes alone", "By independent choices", "Through dialogue and recognition from others and culture", "Randomly"], "ans": 2, "sec": "Logic", "exp": "Identity is dialogically formed through culture and others."},
    {"id": 107, "q": "Aristotle's Forms vs Plato's:", "opts": ["Rejected Forms entirely", "Forms exist in visible things, not separate world", "Forms created by God", "Agreed with Plato"], "ans": 1, "sec": "Logic", "exp": "Aristotle: forms exist within physical objects."},
    {"id": 108, "q": "Confucius on overcoming political strife:", "opts": ["Strict laws and punishments", "Military force", "Virtue in both rulers and citizens", "Economic prosperity alone"], "ans": 2, "sec": "Logic", "exp": "Social harmony comes from cultivating virtue."},
    {"id": 109, "q": "Rationalistic view's essential human characteristic:", "opts": ["Emotion", "Physical strength", "Reason", "Social connection"], "ans": 2, "sec": "Logic", "exp": "Reason defines humans in rationalistic view."},
    {"id": 110, "q": "Feminist critics claim about rationalistic view:", "opts": ["Completely accurate", "Sexist and biased against women", "Needs minor adjustments", "Applies only to ancient times"], "ans": 1, "sec": "Logic", "exp": "Rationalistic view privileges traditionally male traits."},
    {"id": 111, "q": "What makes consciousness 'subjective'?", "opts": ["Can be measured scientifically", "Exists only as experienced by someone, others can't be aware from inside", "Same for everyone", "Purely physical"], "ans": 1, "sec": "Logic", "exp": "Consciousness has first-person perspective only you can access."},
    {"id": 112, "q": "Descartes' view of human nature:", "opts": ["Monism", "Materialism", "Dualism", "Idealism"], "ans": 2, "sec": "Logic", "exp": "Cartesian substance dualism: mind and body distinct."},
    {"id": 113, "q": "Major advocate of behaviorism:", "opts": ["Descartes", "Gilbert Ryle", "John Searle", "David Chalmers"], "ans": 1, "sec": "Logic", "exp": "Gilbert Ryle defended philosophical behaviorism."},
    {"id": 114, "q": "Ryle called Descartes' view:", "opts": ["The soul theory", "The consciousness hypothesis", "The dogma of the ghost in the machine", "The dualist error"], "ans": 2, "sec": "Logic", "exp": "Ghost in the Machine: immaterial mind in physical body."},
    {"id": 115, "q": "Main problem with behaviorism:", "opts": ["Too complicated", "Reduces mind to observable behavior, leaving out interior consciousness", "Contradicts science", "Too old-fashioned"], "ans": 1, "sec": "Logic", "exp": "Behaviorism ignores subjective inner experience."},
    {"id": 116, "q": "Analogy for functionalist view:", "opts": ["Mind like water", "Mind like ghost", "Mind like computer", "Mind like book"], "ans": 2, "sec": "Logic", "exp": "Computer analogy: mind as software, brain as hardware."},
    {"id": 117, "q": "Who developed identity theory?", "opts": ["Descartes", "J.J.C. Smart", "Gilbert Ryle", "John Locke"], "ans": 1, "sec": "Logic", "exp": "J.J.C. Smart developed mind-brain identity theory."},
    {"id": 118, "q": "Searle's 'Chinese Room' argument:", "opts": ["Learning languages", "Following rules can pass Turing Test without understanding Chinese", "Chinese philosophy", "Room design"], "ans": 1, "sec": "Logic", "exp": "Chinese Room: syntax doesn't guarantee understanding."},
    {"id": 119, "q": "Eliminative materialism:", "opts": ["Only physical things exist", "Our ordinary conceptions of mind are false and should be eliminated", "Eliminate the body", "Consciousness doesn't exist"], "ans": 1, "sec": "Logic", "exp": "Folk psychology is false theory to be replaced."},
    {"id": 120, "q": "Philosophy differs from other fields because:", "opts": ["Studies ancient texts only", "Examines fundamental assumptions other fields take for granted", "Requires no evidence", "Focuses on practical problems only"], "ans": 1, "sec": "Logic", "exp": "Philosophy questions foundational assumptions."}
]

st.title("🧠 PHL 201 Comprehensive Exam Quiz - Tutorial Mode")
st.markdown("Test yourself on all 120 questions with instant feedback!")
st.markdown("---")

total = len(questions)
answered = len(st.session_state.answers)
correct = sum(1 for q in questions if st.session_state.answers.get(q['id']) == q['ans'])

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Answered", f"{answered}/{total}")
with col2:
    st.metric("Correct", correct)
with col3:
    pct = (correct/answered*100) if answered > 0 else 0
    st.metric("Score", f"{pct:.1f}%")

st.progress(answered/total)
st.markdown("---")

current_sec = None
for q in questions:
    if q['sec'] != current_sec:
        current_sec = q['sec']
        st.markdown(f"## {current_sec}")
        st.markdown("---")
    
    st.markdown(f"### Question {q['id']}")
    st.markdown(f"**{q['q']}**")
    
    ans = st.radio(
        "Select:",
        range(len(q['opts'])),
        format_func=lambda x, q=q: q['opts'][x],
        key=f"q_{q['id']}",
        index=st.session_state.answers.get(q['id'])
    )
    
    if ans is not None:
        st.session_state.answers[q['id']] = ans
        if ans == q['ans']:
            st.success("✅ Correct!")
        else:
            st.error(f"❌ Incorrect. Answer: **{q['opts'][q['ans']]}**")
        with st.expander("📖 Explanation"):
            st.write(q['exp'])
    st.markdown("---")

if answered == total:
    st.markdown("## 🎉 Complete!")
    st.balloons()
    score = (correct/total)*100
    grade = "A" if score >= 90 else "B" if score >= 80 else "C" if score >= 70 else "D" if score >= 60 else "F"
    st.success(f"### Score: {correct}/{total} ({score:.1f}%) - Grade: {grade}")
